# Generated by Django 6.0.3 on 2026-03-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caughtpokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sprite_url', models.URLField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
